In [2]:
import numpy as np

In [ ]:
## Built in array data types
# get a sense of how arrays are constructed
# run this to play around with multiplication below
a = np.array( [ 1, 2, 3] ) # array takes a list as an input
mat = np.array( np.arange(9).reshape(3,3) ) # quickly build a matrix. arange(n) build array 0:n
a_row = a.reshape(1, a.size )
a_col = a.reshape( a.size, 1 )

In [ ]:
# print to see variables
print('Check size and shapes')
print('a = \n', a) # 1D
print('a_row = \n', a_row) # 2D column
print('a_col= \n', a_col) # 2D row
print('mat = \n', mat) # matrix

In [ ]:
# Test  elementwise multiplication
print('Testing elementwise multiplication and broadcasting')
print( 'a * mat = \n', a * mat ) # multiplies each column of matrix by element of 1D
#print( 'mat * a = \n', mat * a ) # same as above. uncomment to check
print( 'a_row * mat = \n', a_row * mat ) # multiplies each column of matrix by column of row vector
#print( 'mat * a_row = \n', mat * a_row ) # same as above. uncomment to check
print( 'a_col * mat = \n', a_col * mat ) # multiplies each row of matrix by element of 1D
#print( 'mat * a_col = \n', mat * a_col ) # same as above. uncomment to check
#
# Summary: order doesn not matter (a*b) = (b*a). 
# All elementwise multiplication like matlab .* 
# 1D broadcasted like a row vector.')
#

In [ ]:
# Test  matrix multiplication
print('Testing matrix multiplication')
print( 'np.dot(a,mat) = \n', np.dot(a,mat) ) # turn 1D to row, multiply, output 1D
print( 'np.dot(mat,a) = \n', np.dot(mat,a) ) # turn 1D to col, multiply, output 1D
print( 'np.dot(a_row,mat) = \n', np.dot(a_row,mat) ) # multiplies each column of matrix by element of 1D
# fails: print( 'np.dot(mat,a_row) = \n', np.dot(mat,a_row) ) # multiplies each column of matrix by element of 1D
# fails: print( 'np.dot(a_col,mat) = \n', np.dot(a_col,mat) ) # multiplies each column of matrix by element of 1D
print( 'np.dot(mat,a_col) = \n', np.dot(mat,a_col) ) # multiplies each column of matrix by element of 1D
#
# Summary: Use dot to do matrix multiplication 
# Vector math applies as you would expect.
# However, 1D is broadcasted to the appropriate 2D vector,
# multiplied, and the output is a 1D vector.
#

In [ ]:
## Some built in functions similar to MATLAB
# arange( start, stop, delta)
# quick and dirty: arange(end), stop = 0, delta 1
start = 3;
stop = 7;
delta = 2;
a_r = np.arange(start,stop,delta) # or a_r = np.arange(n,1)
print('arange(',start,',',end,',',delta,')=', a_r)
# zeros
n = 2
print( 'zeros( (n,1) ) =\n', np.zeros( (n,1) ) )
print( 'zeros( (n) ) =\n', np.zeros( (n) ) )
print( 'zeros( (n,n) ) =\n',np.zeros( (n,n) ) )

In [1]:
## Indices example: matrix
n = 4;
mat = np.array( np.arange(n*n).reshape(n,n) ) # quickly build a matrix. arange(n) build array 0:n
# doing indices start:stop:delta
stop = 3
delta = 2
str_sep = '%%%%%%%'

print( str_sep,'mat', str_sep  )
print('mat = \n', mat)
print('mat[1,0:4:2] = ', mat[1,0:stop:delta] )
print('mat[:3] = \n', mat[:3] )
print('mat[:3,:] = \n', mat[:3,:] )
print('mat[:,:3] = \n', mat[:,:3] )

NameError: name 'np' is not defined

In [44]:
## Indices example: vector
n = 4;
a = 2 * np.arange( n ) # array takes a list as an input
mat = np.array( np.arange(n*n).reshape(n,n) ) # quickly build a matrix. arange(n) build array 0:n
a_row = a.reshape(1, a.size )
a_col = a.reshape( a.size, 1 )
# doing indices start:stop:delta
inds = [0, 2];
stop = 3
delta = 2
str_sep = '%%%%%%%'
print('stop', stop, 'delta', delta, 'inds', inds )
print( str_sep, 'a', str_sep  )
print('a = ', a)
print('a[0:stop] = ', a[0:stop] )
print('a[1:stop:delta] = ', a[1:stop:delta] )
print('a[inds] = ', a[inds])
print('a[::delta] = ', a[::delta] ) # count by 3s
print( str_sep,'a_row', str_sep  )
print('a_row = ', a_row)
print('a_row[0,:stop] = ', a_row[0,:stop] )
print('a_row[0,inds] = ', a_row[0,inds] )
print('a_row[:stop]/a_row[:stop,:] = ', a_row[:stop] )
print('a_row[:,:stop] = ', a_row[:,:stop] ) 
print('a_row[0,::delta] = ', a_row[0,::delta] ) # count by 2s
#print('a_row[inds] = ', a_row[inds] this breaks, requesting indice is doesn't have
print('a_row[0:2] = ', a_row[0:2] ) 
print( str_sep,'a_col', str_sep  )
print('a_col = \n', a_col)
print('a_col[:stop,0] =', a_col[:stop,0] )
print('a_col[inds,0] = ', a_col[inds,0] )
print('a_col[:stop]/a_col[:stop,:] = \n', a_col[:stop] )
print('a_col[:,:stop] = \n', a_col[:,:stop] )
print('a_col[inds] = \n', a_col[inds] )
print('a_col[0:2] = \n', a_col[0:2] )
print('a_col[::delta,0] = ', a_col[::delta,0] ) # count by 2s
# if a vector is 2D, eg a_row, if we do
# a_row[0:2] without second dimension, 0:2 assumes rows 0:2, column 0. 
# Since all elements are in row 0, this will print the whole vector
# When using :number, if number is greater than the size, that is fine. 
# It just stops when it reaches the end. If you explicity request and element 
# it doesn't have, it breaks

stop 3 delta 2 inds [0, 2]
%%%%%%% a %%%%%%%
a =  [0 2 4 6]
a[0:stop] =  [0 2 4]
a[1:stop:delta] =  [2]
a[inds] =  [0 4]
a[::delta] =  [0 4]
%%%%%%% a_row %%%%%%%
a_row =  [[0 2 4 6]]
a_row[0,:stop] =  [0 2 4]
a_row[0,inds] =  [0 4]
a_row[:stop]/a_row[:stop,:] =  [[0 2 4 6]]
a_row[:,:stop] =  [[0 2 4]]
a_row[0,::delta] =  [0 4]
a_row[0:2] =  [[0 2 4 6]]
%%%%%%% a_col %%%%%%%
a_col = 
 [[0]
 [2]
 [4]
 [6]]
a_col[:stop,0] = [0 2 4]
a_col[inds,0] =  [0 4]
a_col[:stop]/a_col[:stop,:] = 
 [[0]
 [2]
 [4]]
a_col[:,:stop] = 
 [[0]
 [2]
 [4]
 [6]]
a_col[inds] = 
 [[0]
 [4]]
a_col[0:2] = 
 [[0]
 [2]]
a_col[::delta,0] =  [0 4]


In [47]:
## Indices example: matrix
n = 6;
mat = np.array( np.arange(n*n).reshape(n,n) ) # quickly build a matrix. rearrange by columns
# doing indices start:stop:delta
stop = 5
delta = 2
inds = [0, 2];
str_sep = '%%%%%%%'
print('stop', stop, 'delta', delta, 'inds', inds )
print( str_sep,'mat', str_sep  )
print('mat = \n', mat)
print('mat[1,0:stop:delta] = ', mat[1,0:stop:delta] )
print('mat[:stop] = \n', mat[:stop] )
print('mat[:stop,:] = \n', mat[:stop,:] )
print('mat[inds,:] = \n', mat[inds,:] )
print('mat[:,:stop] = \n', mat[:,:stop] )
print('mat[:,inds] = \n', mat[:,inds] )
print('mat.flat[:stop] = \n', mat.flat[:stop] ) # reserve of matlab! Count across columns
print('mat.flat[::delta] = \n', mat.flat[::delta] ) # Count across columns. Count by 10s


stop 5 delta 2 inds [0, 2]
%%%%%%% mat %%%%%%%
mat = 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
mat[1,0:stop:delta] =  [ 6  8 10]
mat[:stop] = 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
mat[:stop,:] = 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
mat[inds,:] = 
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
mat[:,:stop] = 
 [[ 0  1  2  3  4]
 [ 6  7  8  9 10]
 [12 13 14 15 16]
 [18 19 20 21 22]
 [24 25 26 27 28]
 [30 31 32 33 34]]
mat[:,inds] = 
 [[ 0  2]
 [ 6  8]
 [12 14]
 [18 20]
 [24 26]
 [30 32]]
mat.flat[:stop] = 
 [0 1 2 3 4]
mat.flat[::delta] = 
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]
